### ISSUE TITLE
Naming inconsistencies

### ISSUE THREAD

**Issue by chopkins-usgs** [USGS-R/HASP#7]
We use two different names for discrete (hand-measured) data: field groundwater-level measurements (in the data type summary) and periodic data (in the data pull options).  We need to make those names consistent one way or another so that users understand that these are the same measurements.

**Comment by ldecicco-USGS** [comment]
I'd vote "field groundwater-level measurements". Periodic could also easily mean water-quality measurements. I think periodic was written initially because we were assuming this was only going to be used on groundwater. But, it's already pretty flexible that we shouldn't make that assumption right away.
