### ISSUE TITLE
If possible, add labels to pcodes and stat codes in Shiny App

### ISSUE THREAD

**Issue by chopkins-usgs** [USGS-R/HASP#9]
It would be helpful to add the definition of the pcode or stat code so that users understand what data they are pulling. The data for site 374004122092102 varies greatly based on what stat code is being displayed and it would be helpful for a user to understand what these codes mean.

**Comment by ldecicco-USGS** [comment]
From a purely design perspective, this might be a bit of a challenge since sometimes the official names are really long. Maybe not so bad for the daily value pcodes, but certainly for the qw pcodes. 

We might be able to add a tooltip to the dropdown:
https://stackoverflow.com/questions/36132204/reactive-radiobuttons-with-tooltipbs-in-shiny
(adding yet another dependency!)

Maybe first:
(a) just see how good/bad it looks to put the full name in the sidebar
(b) use some smart "gsub"s to get rid of text that is maybe too much info for the side bar (but still display the full name in a graph title or text in the shiny app)

**Comment by chopkins-usgs** [comment]
It would be fantastic to do this for quantity info.  I think we leave that option off for qw pcodes.

**Comment by ldecicco-USGS** [comment]
Anyone know off hand if they ever added a "stat code lookup" service in NWIS? Something like:
https://nwis.waterdata.usgs.gov/nwis/pmcode
but will let you get the stat code official names?
If so, it would be great to add that to dataRetrieval...which would then let the dropdown of stat codes be more programatic

**Comment by chopkins-usgs** [comment]
That is the only lookup site I am aware of.  I personally am unaware of a stat lookup service.
